const K={theme:"ygmhelper.theme",language:"ygmhelper.language",date:"ygmhelper.date",grade:"ygmhelper.timetableGrade",classNumber:"ygmhelper.timetableClass"};
const T={ko:{navTimetable:"시간표",navMeal:"급식표",eyebrow:"오늘",pageTitle:"학교 정보",refresh:"새로고침",today:"오늘",mealKicker:"Meal",mealTitle:"급식표",timetableKicker:"Timetable",timetableTitle:"시간표",grade:"학년",class:"반",loading:"불러오는 중...",allergyGuide:"알레르기 안내",allergyTitle:"알레르기 안내",noMeal:"등록된 급식 정보가 없습니다.",noTimetable:"등록된 시간표 정보가 없습니다.",mealError:"급식 정보를 불러오지 못했습니다.",timetableError:"시간표 정보를 불러오지 못했습니다.",calories:"열량",period:"교시",previousDay:"이전 날짜",nextDay:"다음 날짜",close:"닫기",themeToLight:"라이트 모드로 전환",themeToDark:"다크 모드로 전환"},en:{navTimetable:"Timetable",navMeal:"Meal",eyebrow:"Today",pageTitle:"School Info",refresh:"Refresh",today:"Today",mealKicker:"Meal",mealTitle:"Meal",timetableKicker:"Timetable",timetableTitle:"Timetable",grade:"Grade",class:"Class",loading:"Loading...",allergyGuide:"Allergy guide",allergyTitle:"Allergy Information",noMeal:"No meal information is available.",noTimetable:"No timetable information is available.",mealError:"Unable to load meal information.",timetableError:"Unable to load timetable information.",calories:"Calories",period:"Period",previousDay:"Previous day",nextDay:"Next day",close:"Close",themeToLight:"Switch to light mode",themeToDark:"Switch to dark mode"}};
const A={ko:["난류","우유","메밀","땅콩","대두","밀","고등어","게","새우","돼지고기","복숭아","토마토","아황산류","호두","닭고기","쇠고기","오징어","조개류 (굴, 전복, 홍합 포함)","잣"],en:["Eggs","Milk","Buckwheat","Peanuts","Soybeans","Wheat","Mackerel","Crab","Shrimp","Pork","Peach","Tomato","Sulfites","Walnuts","Chicken","Beef","Squid","Shellfish (oyster, abalone, mussel)","Pine nuts"]};
const state={language:localStorage.getItem(K.language)||((navigator.language||"").toLowerCase().startsWith("ko")?"ko":"en"),theme:document.documentElement.dataset.theme,date:localStorage.getItem(K.date)||today(),grade:num(K.grade,1,3),classNumber:num(K.classNumber,1,15)};
const $=s=>document.querySelector(s), els={date:$("#date-picker"),prev:$("#previous-day"),next:$("#next-day"),today:$("#today-button"),refresh:$("#refresh-button"),meal:$("#meal-content"),mealDate:$("#meal-date-label"),tt:$("#timetable-content"),ttDate:$("#timetable-date-label"),grade:$("#grade-select"),cls:$("#class-select"),theme:$("#theme-toggle"),langs:[...document.querySelectorAll(".language-button")],allergy:$("#allergy-button"),modal:$("#allergy-modal"),close:$("#close-allergy-modal"),allergyList:$("#allergy-list")};
document.addEventListener("DOMContentLoaded",init);
function init(){for(let i=1;i<=3;i++)els.grade.add(new Option(i,i));for(let i=1;i<=15;i++)els.cls.add(new Option(i,i));bind();applyLanguage();applyTheme(state.theme);sync();load();}
function bind(){els.date.onchange=()=>{if(els.date.value){state.date=els.date.value;localStorage.setItem(K.date,state.date);sync();load();}};els.prev.onclick=()=>move(-1);els.next.onclick=()=>move(1);els.today.onclick=()=>{state.date=today();localStorage.setItem(K.date,state.date);sync();load();};els.refresh.onclick=load;els.grade.onchange=()=>{state.grade=+els.grade.value;localStorage.setItem(K.grade,state.grade);load()};els.cls.onchange=()=>{state.classNumber=+els.cls.value;localStorage.setItem(K.classNumber,state.classNumber);load()};els.langs.forEach(b=>b.onclick=()=>{state.language=b.dataset.language;localStorage.setItem(K.language,state.language);applyLanguage();sync();load()});els.theme.onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";localStorage.setItem(K.theme,state.theme);applyTheme(state.theme)};els.allergy.onclick=openModal;els.close.onclick=closeModal;els.modal.onclick=e=>{if(e.target.matches("[data-modal-close]"))closeModal()};document.onkeydown=e=>{if(e.key==="Escape"&&!els.modal.hidden)closeModal()}};
function move(n){const d=new Date(state.date+"T00:00:00");d.setDate(d.getDate()+n);state.date=fmt(d);localStorage.setItem(K.date,state.date);sync();load()}
async function load(){els.meal.innerHTML=els.tt.innerHTML='<div class="loading-state">'+t("loading")+"</div>";const [m,tt]=await Promise.allSettled([get("/api/meal?date="+apiDate(state.date)),get("/api/timetable?date="+apiDate(state.date)+"&grade="+state.grade+"&class="+state.classNumber)]);m.status==="fulfilled"?meal(m.value):error(els.meal,t("mealError"));tt.status==="fulfilled"?timetable(tt.value):error(els.tt,t("timetableError"))}
async function get(u){const r=await fetch(u,{headers:{Accept:"application/json"}});const d=await r.json();if(!r.ok||d.ok===false)throw Error();return d}
function meal(d){els.meal.innerHTML="";if(!d.meals?.length){empty(els.meal,t("noMeal"));return}const x=d.meals.find(v=>v.mealName==="중식")||d.meals[0],sum=document.createElement("div");sum.className="meal-summary";sum.innerHTML='<p class="meal-name"></p><span class="meal-calories"></span>';sum.querySelector(".meal-name").textContent=x.mealName||"중식";sum.querySelector(".meal-calories").textContent=x.calories?t("calories")+" "+x.calories:"";const ul=document.createElement("ul");ul.className="menu-list";x.menu.forEach(v=>{const li=document.createElement("li");li.className="menu-item";const n=document.createElement("span"),a=document.createElement("span");n.className="menu-name";a.className="allergy-numbers";n.textContent=v.name;a.textContent=v.allergens.join(".");li.append(n,a);ul.append(li)});els.meal.append(sum,ul)}
function timetable(d){els.tt.innerHTML="";if(!d.periods?.length){empty(els.tt,t("noTimetable"));return}const ol=document.createElement("ol");ol.className="timetable-list";d.periods.forEach(v=>{const li=document.createElement("li");li.className="period-row";li.innerHTML='<span class="period-number"></span><span class="subject"></span>';li.firstChild.textContent=v.period+t("period");li.lastChild.textContent=v.subject;ol.append(li)});els.tt.append(ol)}
function empty(c,m){c.innerHTML="";const x=document.createElement("div");x.className="empty-state";x.textContent=m;c.append(x)}function error(c,m){c.innerHTML="";const x=document.createElement("div");x.className="error-state";x.textContent=m;c.append(x)}
function applyLanguage(){document.documentElement.lang=state.language;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));els.langs.forEach(b=>b.classList.toggle("active",b.dataset.language===state.language));renderAllergy();themeButton()}
function applyTheme(x){document.documentElement.dataset.theme=x;themeButton()}function themeButton(){els.theme.textContent=state.theme==="dark"?"☀":"☾";els.theme.setAttribute("aria-label",t(state.theme==="dark"?"themeToLight":"themeToDark"))}
function renderAllergy(){els.allergyList.innerHTML="";A[state.language].forEach((n,i)=>{const x=document.createElement("div");x.className="allergy-item";x.innerHTML='<span class="allergy-number"></span><span class="allergy-name"></span>';x.firstChild.textContent=i+1;x.lastChild.textContent=n;els.allergyList.append(x)})}
function openModal(){renderAllergy();els.modal.hidden=false;document.body.style.overflow="hidden";els.close.focus()}function closeModal(){els.modal.hidden=true;document.body.style.overflow="";els.allergy.focus()}
function sync(){els.date.value=state.date;els.grade.value=state.grade;els.cls.value=state.classNumber;const d=label(state.date);els.mealDate.textContent=els.ttDate.textContent=d;els.prev.setAttribute("aria-label",t("previousDay"));els.next.setAttribute("aria-label",t("nextDay"));els.close.setAttribute("aria-label",t("close"))}
function t(k){return T[state.language][k]||k}function today(){const d=new Date(),p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d),v=Object.fromEntries(p.map(x=>[x.type,x.value]));return v.year+"-"+v.month+"-"+v.day}
function fmt(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}function label(s){return new Intl.DateTimeFormat(state.language==="ko"?"ko-KR":"en-US",{month:"short",day:"numeric",weekday:"short"}).format(new Date(s+"T00:00:00"))}function apiDate(s){return s.replaceAll("-","")}function num(k,f,max){const n=+localStorage.getItem(k);return Number.isInteger(n)&&n>=1&&n<=max?n:f}